### ISSUE TITLE
Add official badge

### ISSUE THREAD

**Issue by ericdouglas** [open-source-society/bioinformatics#2]
Maybe we can put an official badge in this repository, so students will be able to link back to this in their own projects.

Example: [![Open Source Society University - Bioinformatics](https://img.shields.io/badge/OSSU-bioinformatics-blue.svg)](https://github.com/open-source-society/bioinformatics)

- Markdown: `[![Open Source Society University - Bioinformatics](https://img.shields.io/badge/OSSU-bioinformatics-blue.svg)](https://github.com/open-source-society/bioinformatics)`
- HTML: `<a href="https://github.com/open-source-society/bioinformatics"><img alt="Open Source Society University - Bioinformatics" src="https://img.shields.io/badge/OSSU-bioinformatics-blue.svg"></a>`

:smile:

**Comment by eneskemalergin** [comment]
I added the badge  with this [commit](https://github.com/open-source-society/bioinformatics/commit/7a09b96d1264c16ad1625b3c609f4c30fd917504) thanks 👍

**Comment by ericdouglas** [comment]
@eneskemalergin many thanks!
