### ISSUE TITLE
README updates

### ISSUE THREAD

**Issue by ericdouglas** [open-source-society/bioinformatics#3]
@eneskemalergin Some things to be updated in the README

- [x] Remove section [Becoming an OSS student](https://github.com/open-source-society/bioinformatics#becoming-an-oss-student) from TOC and also remove the content.
- [x] In "Order of the classes" section, change the last statement for: "**OBS**: If the course is not open, do it with the archived resources or wait until next class is open."

**Comment by eneskemalergin** [comment]
done
