### ISSUE TITLE
Suggestion - Add Molecular Biology 3 

### ISSUE THREAD

**Issue by fabianomenegidio** [open-source-society/bioinformatics#5]
BIO 4312c | [Molecular Biology 3 ](hhttps://www.edx.org/course/molecular-biology-part-3-rna-processing-mitx-7-28-3x-0) | 8 Weeks | 4-8 Hours/Week

**Comment by eneskemalergin** [comment]
@fabianomenegidio where exactly is this course? I did not check the recent courses for a while.

**Comment by fabianomenegidio** [comment]
Sorry, I did not see that I did not paste the link.

https://www.edx.org/course/molecular-biology-part-3-rna-processing-mitx-7-28-3x-0

**Comment by eneskemalergin** [comment]
@fabianomenegidio, thanks I've added Mol Bio 3 to the list.
