### ISSUE TITLE
Suggestion - Maybe to add some youtube videos

### ISSUE THREAD

**Issue by AndyZhuang** [open-source-society/bioinformatics#7]
Would it be ok to add some of the short but owesome youtube videos on the list?   such as  Thermo Fisher Scientific 's  "Seq it out"  ,  and a list of that would be great.

**Comment by locovna** [comment]
Maybe it would be easer if you provide some links? @AndyZhuang

**Comment by eneskemalergin** [comment]
@AndyZhuang, it's a nice request we could definitely add them as extra sources. If you could provide some links, it will be fast.

**Comment by AndyZhuang** [comment]
Ok, I will try to add some links ,  thanks much, this is a great project.
